[build]
  command = "yarn build && cp dist/netlify/functions/*.js netlify/functions-built/"
  functions = "netlify/functions-built"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/graphql"
  status = 200

[[redirects]]
  from = "/graphql/*"
  to = "/.netlify/functions/graphql"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 